# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  backend-test:
    build:
      context: ./fastapi
      args:
        TEST: "true"
    entrypoint: ["pytest", "--maxfail=1", "-v" ,  "-rs"]
    volumes:
      - ./fastapi:/app

  frontend:
    build:
      context: ./hackernews-react
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - backend
